# Site wide configuration
title:            Andrey Kurenkov's Web World
locale:           en_US
url:                          

# Jekyll configuration
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: assets/_sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
flickr:
  screen_name: You
  api_key: 0bf2bfeccdaa58f2e650dabd190d9c1a
  api_secret: 53949e12d158e9e6
  cache_dir: _flickr
  use_cache: true

# Site owner
owner:
  name: Andrey Kurenkov
  avatar: andrey.gif
  bio: "An eclectic researcher and engineer interested in AI, art, side-projects, philosophy, and many more things."
  email: contact@andreykurenkov.com
  google:
    analytics: UA-54402578-2
  disqus-shortname: eclecticcreations
  github: andreykurenkov
  linkedin: andreykurenkov
#  letterboxd: andreykurenkov

include: [".htaccess",'_pages']
exclude: ["lib", "config.rb", "_deploy.yml", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md","images/instagramget.txt","serve_jekyll","assets/css/bootstrap.min.css","assets/css/main.css","assets/js/plugins/",".deploy"]
